version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yomikikase-app
    ports:
      - "3005:3005"
    volumes:
      # ソースコードをマウント（ホットリロード対応）
      - .:/app
      # node_modulesは除外してパフォーマンス向上
      - /app/node_modules
      # MCP設定のマウント
      - ./mcp-config:/app/.mcp
    environment:
      - NODE_ENV=development
      - PORT=3005
      - MCP_CONFIG_PATH=/app/.mcp
    command: npm run dev
    stdin_open: true
    tty: true

  # MCPサーバー（必要に応じて追加）
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yomikikase-mcp
    volumes:
      - .:/app
      - /app/node_modules
      - ./mcp-config:/app/.mcp
    environment:
      - NODE_ENV=development
      - MCP_SERVER_PORT=4006
    command: npm run mcp:server
    ports:
      - "4006:4006"
    depends_on:
      - app

  # データベース（必要に応じて追加）
  db:
    image: postgres:15-alpine
    container_name: yomikikase-db
    environment:
      - POSTGRES_DB=yomikikase
      - POSTGRES_USER=yomikikase
      - POSTGRES_PASSWORD=yomikikase_dev_password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis（キャッシュ用、必要に応じて）
  redis:
    image: redis:7-alpine
    container_name: yomikikase-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data: